// Code generated by gen. DO NOT EDIT.

package entity

import "time"

type LinkInfo_InsertLinksParams struct {
	Ids              []string
	Usernames        []string
	Amounts          []float64
	Links            []string
	Descriptions     []string
	Createddatetimes []time.Time
	Updateddatetimes []time.Time
}

type LinkInfo_ListAllLinkRow struct {
	ID              string
	Username        string
	Amount          float64
	Link            string
	Description     string
	CreatedDatetime time.Time
	UpdatedDatetime time.Time
}

type LinkInfo_ListLinkByUsernameRow struct {
	ID              string
	Username        string
	Amount          float64
	Link            string
	Description     string
	CreatedDatetime time.Time
	UpdatedDatetime time.Time
}

type LinkInfo struct {
	ID              string
	Amount          float64
	Username        string
	Link            string
	Description     string
	CreatedDatetime time.Time
	UpdatedDatetime time.Time
}

type User struct {
	ID              string
	Username        string
	FirstName       string
	LastName        string
	CreatedDatetime time.Time
	UpdatedDatetime time.Time
}

type User_GetAllUsersParams struct {
	Offset int32
	Limit  int32
}
