// Code generated by gen. DO NOT EDIT.

package entity

import (
	"time"

	"github.com/chonlatee/payment/internal/dbgen"
	"github.com/chonlatee/payment/internal/lib/converter"
)

func LinkInfo_InsertLinksParamsToModel(input LinkInfo_InsertLinksParams) (*dbgen.LinkInfo_InsertLinksParams, error) {
	var err error
	v := &dbgen.LinkInfo_InsertLinksParams{}

	r, err := converter.StringsToPgTypeUUIDs(input.Ids)
	if err != nil {
		return nil, err
	}
	v.Ids = r

	v.Usernames = input.Usernames

	r, err := []float64
	if err != nil {
		return nil, err
	}
	v.Amounts = r

	v.Links = input.Links

	v.Descriptions = input.Descriptions

	r, err := []time.Time
	if err != nil {
		return nil, err
	}
	v.Createddatetimes = r

	r, err := []time.Time
	if err != nil {
		return nil, err
	}
	v.Updateddatetimes = r

	return v, nil
}

func LinkInfo_ListAllLinkRowToModel(input LinkInfo_ListAllLinkRow) (*dbgen.LinkInfo_ListAllLinkRow, error) {
	var err error
	v := &dbgen.LinkInfo_ListAllLinkRow{}

	r, err := string
	if err != nil {
		return nil, err
	}
	v.ID = r

	v.Username = input.Username

	r, err := float64
	if err != nil {
		return nil, err
	}
	v.Amount = r

	v.Link = input.Link

	r, err := string
	if err != nil {
		return nil, err
	}
	v.Description = r

	r, err := time.Time
	if err != nil {
		return nil, err
	}
	v.CreatedDatetime = r

	r, err := time.Time
	if err != nil {
		return nil, err
	}
	v.UpdatedDatetime = r

	return v, nil
}

func LinkInfo_ListLinkByUsernameRowToModel(input LinkInfo_ListLinkByUsernameRow) (*dbgen.LinkInfo_ListLinkByUsernameRow, error) {
	var err error
	v := &dbgen.LinkInfo_ListLinkByUsernameRow{}

	r, err := string
	if err != nil {
		return nil, err
	}
	v.ID = r

	v.Username = input.Username

	r, err := float64
	if err != nil {
		return nil, err
	}
	v.Amount = r

	v.Link = input.Link

	r, err := string
	if err != nil {
		return nil, err
	}
	v.Description = r

	r, err := time.Time
	if err != nil {
		return nil, err
	}
	v.CreatedDatetime = r

	r, err := time.Time
	if err != nil {
		return nil, err
	}
	v.UpdatedDatetime = r

	return v, nil
}

func LinkInfoToModel(input LinkInfo) (*dbgen.LinkInfo, error) {
	var err error
	v := &dbgen.LinkInfo{}

	r, err := string
	if err != nil {
		return nil, err
	}
	v.ID = r

	r, err := float64
	if err != nil {
		return nil, err
	}
	v.Amount = r

	v.Username = input.Username

	v.Link = input.Link

	r, err := string
	if err != nil {
		return nil, err
	}
	v.Description = r

	r, err := time.Time
	if err != nil {
		return nil, err
	}
	v.CreatedDatetime = r

	r, err := time.Time
	if err != nil {
		return nil, err
	}
	v.UpdatedDatetime = r

	return v, nil
}

func UserToModel(input User) (*dbgen.User, error) {
	var err error
	v := &dbgen.User{}

	r, err := string
	if err != nil {
		return nil, err
	}
	v.ID = r

	v.Username = input.Username

	v.FirstName = input.FirstName

	v.LastName = input.LastName

	r, err := time.Time
	if err != nil {
		return nil, err
	}
	v.CreatedDatetime = r

	r, err := time.Time
	if err != nil {
		return nil, err
	}
	v.UpdatedDatetime = r

	return v, nil
}

func User_GetAllUsersParamsToModel(input User_GetAllUsersParams) (*dbgen.User_GetAllUsersParams, error) {
	var err error
	v := &dbgen.User_GetAllUsersParams{}

	v.Offset = input.Offset

	v.Limit = input.Limit

	return v, nil
}
