// Code generated by gen. DO NOT EDIT.

package entity

import (
	"github.com/chonlatee/payment/internal/dbgen"
	"github.com/chonlatee/payment/internal/lib/converter"
)

func LinkInfo_InsertLinksParamsToEntity(input dbgen.LinkInfo_InsertLinksParams) (*LinkInfo_InsertLinksParams, error) {
	v := &LinkInfo_InsertLinksParams{}

	r0, err0 := converter.PgtypeUUIDsToStrings(input.Ids)
	if err0 != nil {
		return nil, err0
	}
	v.Ids = r0

	v.Usernames = input.Usernames

	r2, err2 := converter.PgtypeNumericsToFloat64s(input.Amounts)
	if err2 != nil {
		return nil, err2
	}
	v.Amounts = r2

	v.Links = input.Links

	v.Descriptions = input.Descriptions

	r5, err5 := converter.PgtypeTimestamptzsToTimes(input.Createddatetimes)
	if err5 != nil {
		return nil, err5
	}
	v.Createddatetimes = r5

	r6, err6 := converter.PgtypeTimestamptzsToTimes(input.Updateddatetimes)
	if err6 != nil {
		return nil, err6
	}
	v.Updateddatetimes = r6

	return v, nil
}

func LinkInfo_ListAllLinkRowToEntity(input dbgen.LinkInfo_ListAllLinkRow) (*LinkInfo_ListAllLinkRow, error) {
	v := &LinkInfo_ListAllLinkRow{}

	r0, err0 := converter.PgtypeUUIDToString(input.ID)
	if err0 != nil {
		return nil, err0
	}
	v.ID = r0

	v.Username = input.Username

	r2, err2 := converter.PgtypeNumericToFloat64(input.Amount)
	if err2 != nil {
		return nil, err2
	}
	v.Amount = r2

	v.Link = input.Link

	r4, err4 := converter.PgtypeTextToString(input.Description)
	if err4 != nil {
		return nil, err4
	}
	v.Description = r4

	r5, err5 := converter.PgtypeTimestamptzToTime(input.CreatedDatetime)
	if err5 != nil {
		return nil, err5
	}
	v.CreatedDatetime = r5

	r6, err6 := converter.PgtypeTimestamptzToTime(input.UpdatedDatetime)
	if err6 != nil {
		return nil, err6
	}
	v.UpdatedDatetime = r6

	return v, nil
}

func LinkInfo_ListLinkByUsernameRowToEntity(input dbgen.LinkInfo_ListLinkByUsernameRow) (*LinkInfo_ListLinkByUsernameRow, error) {
	v := &LinkInfo_ListLinkByUsernameRow{}

	r0, err0 := converter.PgtypeUUIDToString(input.ID)
	if err0 != nil {
		return nil, err0
	}
	v.ID = r0

	v.Username = input.Username

	r2, err2 := converter.PgtypeNumericToFloat64(input.Amount)
	if err2 != nil {
		return nil, err2
	}
	v.Amount = r2

	v.Link = input.Link

	r4, err4 := converter.PgtypeTextToString(input.Description)
	if err4 != nil {
		return nil, err4
	}
	v.Description = r4

	r5, err5 := converter.PgtypeTimestamptzToTime(input.CreatedDatetime)
	if err5 != nil {
		return nil, err5
	}
	v.CreatedDatetime = r5

	r6, err6 := converter.PgtypeTimestamptzToTime(input.UpdatedDatetime)
	if err6 != nil {
		return nil, err6
	}
	v.UpdatedDatetime = r6

	return v, nil
}

func LinkInfoToEntity(input dbgen.LinkInfo) (*LinkInfo, error) {
	v := &LinkInfo{}

	r0, err0 := converter.PgtypeUUIDToString(input.ID)
	if err0 != nil {
		return nil, err0
	}
	v.ID = r0

	r1, err1 := converter.PgtypeNumericToFloat64(input.Amount)
	if err1 != nil {
		return nil, err1
	}
	v.Amount = r1

	v.Username = input.Username

	v.Link = input.Link

	r4, err4 := converter.PgtypeTextToString(input.Description)
	if err4 != nil {
		return nil, err4
	}
	v.Description = r4

	r5, err5 := converter.PgtypeTimestamptzToTime(input.CreatedDatetime)
	if err5 != nil {
		return nil, err5
	}
	v.CreatedDatetime = r5

	r6, err6 := converter.PgtypeTimestamptzToTime(input.UpdatedDatetime)
	if err6 != nil {
		return nil, err6
	}
	v.UpdatedDatetime = r6

	return v, nil
}

func UserToEntity(input dbgen.User) (*User, error) {
	v := &User{}

	r0, err0 := converter.PgtypeUUIDToString(input.ID)
	if err0 != nil {
		return nil, err0
	}
	v.ID = r0

	v.Username = input.Username

	v.FirstName = input.FirstName

	v.LastName = input.LastName

	r4, err4 := converter.PgtypeTimestamptzToTime(input.CreatedDatetime)
	if err4 != nil {
		return nil, err4
	}
	v.CreatedDatetime = r4

	r5, err5 := converter.PgtypeTimestamptzToTime(input.UpdatedDatetime)
	if err5 != nil {
		return nil, err5
	}
	v.UpdatedDatetime = r5

	return v, nil
}

func User_GetAllUsersParamsToEntity(input dbgen.User_GetAllUsersParams) (*User_GetAllUsersParams, error) {
	v := &User_GetAllUsersParams{}

	v.Offset = input.Offset

	v.Limit = input.Limit

	return v, nil
}
