// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID              pgtype.UUID
	Name            string
	Bio             pgtype.Text
	CreatedDatetime pgtype.Timestamptz
	UpdatedDatetime pgtype.Timestamptz
}

type Book struct {
	ID              pgtype.UUID
	Author          pgtype.UUID
	Title           string
	Description     pgtype.Text
	Price           pgtype.Numeric
	CreatedDatetime pgtype.Timestamptz
	UpdatedDatetime pgtype.Timestamptz
	RevokeDatetime  pgtype.Timestamptz
}
