// Code generated by gen. DO NOT EDIT.

package entity


{{- range getEntityList }}

type  {{ getEntityName .}} struct {
{{- range getEntityFields .}}
    {{ getEntityFieldName .}} {{ getEntityFieldType .}}
{{- end}}

}
{{- end}}