// Code generated by gen. DO NOT EDIT.

package entity

{{- range getEntityList }}


func {{ getEntityName .}}ToModel(input {{ getEntityName .}}) (*dbgen.{{ getModelName .}}, error) {
    v := &dbgen.{{ getModelName .}}{}
{{- range $i, $f := getEntityFields .}}

    {{ if needConvert .}}

    r{{ $i }}, err{{ $i }} := {{ getEntityFieldValue .}}
    if err{{ $i }} != nil {
        return nil, err{{ $i }}
    }
    v.{{ getEntityFieldName .}} = r{{ $i }}
    {{ else }}
    v.{{ getEntityFieldName .}} = input.{{ getEntityFieldName .}}
    {{ end }}

{{- end}}
    return v, nil
}
{{- end}}