// Code generated by gen. DO NOT EDIT.

package entity

{{- range getEntityList }}


func {{ getEntityName .}}ToModel(input {{ getEntityName .}}) (*dbgen.{{ getModelName .}}, error) {
    var err error
    v := &dbgen.{{ getModelName .}}{}
{{- range getEntityFields .}}

    {{ if needConvert .}}

    r, err := {{ getEntityFieldValue .}}
    if err != nil {
        return nil, err
    }
    v.{{ getEntityFieldName .}} = r
    {{ else }}
    v.{{ getEntityFieldName .}} = input.{{ getEntityFieldName .}}
    {{ end }}

{{- end}}
    return v, nil
}
{{- end}}