// Code generated by gen. DO NOT EDIT.

package entity

{{- range getEntityList }}


func {{ getModelName .}}ToEntity(input dbgen.{{ getEntityName .}}) (*{{ getEntityName .}}, error) {
    v := &{{ getEntityName .}}{}
{{- range $i, $f := getEntityFields .}}

    {{ if needConvert .}}

    r{{ $i }}, err{{ $i }} := {{ getModelFieldValue .}}
    if err{{ $i }} != nil {
        return nil, err{{ $i }}
    }
    v.{{ getEntityFieldName .}} = r{{ $i }}

    {{ else }}

    v.{{ getEntityFieldName .}} = input.{{ getEntityFieldName .}}

    {{ end }}

{{- end}}
    return v, nil
}
{{- end}}