// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: link.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAllLink = `-- name: ListAllLink :many
select id, username, amount, link, created_datetime, updated_datetime from link_info
`

type ListAllLinkRow struct {
	ID              pgtype.UUID
	Username        string
	Amount          pgtype.Numeric
	Link            string
	CreatedDatetime pgtype.Timestamptz
	UpdatedDatetime pgtype.Timestamptz
}

func (q *Queries) ListAllLink(ctx context.Context) ([]ListAllLinkRow, error) {
	rows, err := q.db.Query(ctx, listAllLink)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllLinkRow
	for rows.Next() {
		var i ListAllLinkRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Amount,
			&i.Link,
			&i.CreatedDatetime,
			&i.UpdatedDatetime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinkByUsername = `-- name: ListLinkByUsername :many
select id, username, amount, link, created_datetime, updated_datetime from link_info where username = $1
`

type ListLinkByUsernameRow struct {
	ID              pgtype.UUID
	Username        string
	Amount          pgtype.Numeric
	Link            string
	CreatedDatetime pgtype.Timestamptz
	UpdatedDatetime pgtype.Timestamptz
}

func (q *Queries) ListLinkByUsername(ctx context.Context, username string) ([]ListLinkByUsernameRow, error) {
	rows, err := q.db.Query(ctx, listLinkByUsername, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLinkByUsernameRow
	for rows.Next() {
		var i ListLinkByUsernameRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Amount,
			&i.Link,
			&i.CreatedDatetime,
			&i.UpdatedDatetime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
