// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type LinkInfo struct {
	ID              pgtype.UUID
	Amount          pgtype.Numeric
	Username        string
	Link            string
	Description     pgtype.Text
	CreatedDatetime pgtype.Timestamptz
	UpdatedDatetime pgtype.Timestamptz
}

type User struct {
	ID              pgtype.UUID
	Username        string
	FirstName       string
	LastName        string
	CreatedDatetime pgtype.Timestamptz
	UpdatedDatetime pgtype.Timestamptz
}
