// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const user_GetAllUsers = `-- name: User_GetAllUsers :many
select id, username, first_name, last_name, created_datetime, updated_datetime from "user" offset $1 limit $2
`

type User_GetAllUsersParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) User_GetAllUsers(ctx context.Context, arg User_GetAllUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, user_GetAllUsers, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.CreatedDatetime,
			&i.UpdatedDatetime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const user_GetUserByID = `-- name: User_GetUserByID :one
select id, username, first_name, last_name, created_datetime, updated_datetime from "user" where id = $1
`

func (q *Queries) User_GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, user_GetUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.CreatedDatetime,
		&i.UpdatedDatetime,
	)
	return i, err
}

const user_GetUserByUserName = `-- name: User_GetUserByUserName :one
select id, username, first_name, last_name, created_datetime, updated_datetime from "user" where username = $1
`

func (q *Queries) User_GetUserByUserName(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, user_GetUserByUserName, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.CreatedDatetime,
		&i.UpdatedDatetime,
	)
	return i, err
}
